name: Crayon4626

arbitrum:
  default_network: mainnet
  mainnet:
    default_provider: geth
  mainnet_fork:
    default_provider: foundry

geth:
  arbitrum:
    mainnet:
      uri: https://arb1.arbitrum.io/rpc

foundry:
  host: auto

vyper:
  version: 0.3.10
  evm_version: paris